#!/usr/bin/env bash
set -e

echo "=============================="
echo " forge-secure-deploy wizard   "
echo "=============================="
echo ""

if [ -f "deploy.toml" ]; then
    read -p "⚠️  A deploy.toml already exists. Overwrite? (y/n): " overwrite
    if [[ "$overwrite" != "y" ]]; then
        echo "Setup aborted. Existing deploy.toml kept."
        exit 0
    fi
fi

# Hardcoded local anvil defaults
ACCOUNTS="[accounts]\nlocal        = \"anvil\"\n"
ADDRESSES="[addresses]\nlocal        = \"0xf39Fd6e51aad88F6F4ce6aB8827279cffFb92266\"\n"
RPC="[rpc]\nlocal        = \"http://127.0.0.1:8545\"\n"

echo "Which networks do you want to configure? (e.g., sepolia mainnet base)"
read -p "Networks: " input_networks
networks=($input_networks)

for net in "${networks[@]}"; do
    echo ""
    echo "------------------------------"
    echo " Setting up network: $net"
    echo "------------------------------"
    
    read -p "Keystore name for $net? (e.g., myWallet): " keystore
    
    # Check if keystore exists before importing
    if ! cast wallet address --account "$keystore" >/dev/null 2>&1; then
        echo "Keystore '$keystore' not found. Let's import your private key."
        cast wallet import "$keystore"
    else
        echo "Keystore '$keystore' already exists. Skipping import."
    fi
    
    echo "Deriving address..."
    address=$(cast wallet address --account "$keystore")
    
    echo "→ Derived automatically: $address"
    
    # Format RPC variable name (e.g., SEPOLIA_RPC_URL)
    net_upper=$(echo "$net" | tr '[:lower:]' '[:upper:]')
    rpc_env_var="${net_upper}_RPC_URL"
    rpc_url="\${${rpc_env_var}}"
    
    # Append to sections with formatting
    ACCOUNTS+=$(printf "%-12s = \"%s\"\n" "$net" "$keystore")
    ADDRESSES+=$(printf "%-12s = \"%s\"\n" "$net" "$address")
    RPC+=$(printf "%-12s = \"%s\"\n" "$net" "$rpc_url")
done

echo ""
echo "Writing deploy.toml..."

echo -e "# Auto-generated by forge-secure-deploy\n# Safe to commit — no secrets here\n\n${ACCOUNTS}\n${ADDRESSES}\n${RPC}" > deploy.toml

echo "✅ deploy.toml complete"
echo "You can now safely commit deploy.toml to your repo."
echo "Done — never think about addresses or keystore names again!"
